version: '2'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=stockdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passw0rd
    

  server:
    user: root
    build: ./server
    command: bash -c "cd /temp && chmod 777 run.sh && ./run.sh"
    volumes:
      - ./server:/temp
    ports:
      - "12345:12345"
    depends_on:
      - db