SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
DROP TABLE IF EXISTS POSITIONS CASCADE;
DROP TABLE IF EXISTS ACCOUNTS CASCADE;
DROP TABLE IF EXISTS ORDERS CASCADE;
DROP TABLE IF EXISTS OPENORDER CASCADE;


CREATE TABLE IF NOT EXISTS ACCOUNTS(
    ACCOUNT_ID INT PRIMARY KEY NOT NULL,
    BALANCE DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (BALANCE >= 0)
);

CREATE TABLE IF NOT EXISTS POSITIONS(
    ACCOUNT_ID INT NOT NULL,
    SYM VARCHAR(256) NOT NULL,
    AMOUNT DOUBLE PRECISION  NOT NULL DEFAULT 0 CHECK (AMOUNT >= 0),
    PRIMARY KEY (ACCOUNT_ID, SYM),
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS OPENORDER(
    TRANS_ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT,
    SYM VARCHAR(256) NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL DEFAULT 0,
    LIMITS DOUBLE PRECISION NOT NULL,
    STATUS VARCHAR(256) NOT NULL DEFAULT 'open',
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID SERIAL PRIMARY KEY,
    TRANS_ID INT NOT NULL,
    SYM VARCHAR(256) NOT NULL,
    AMOUNT DOUBLE PRECISION NOT NULL DEFAULT 0,
    STATUS VARCHAR(256) NOT NULL,
    TIME BIGINT,
    ACCOUNT_ID INT,
    PRICE DOUBLE PRECISION DEFAULT 0,   
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID) ON DELETE CASCADE
);






